version: '3.8'

services:
  ai:
    build: .
    container_name: ai-news-flask
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://spring:8080/api/summaries
      - ID=KVztVt2K9FcNLM_8kXLD
      - SECRET_KEY=UCd_GtcK7T
      - KEYWORD_URL=https://api.signal.bz/news/realtime
    restart: unless-stopped
    depends_on:
      - spring
    networks:
      - news-network

networks:
  news-network:
    external: true  # 이미 정의된 경우 (아니면 false 또는 생략 가능)
